### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by attrib** [attrib/RepairRecipe#13]
```
    2012-08-20 17:47:37 [SEVERE] Could not pass event InventoryClickEvent to RepairRecipe
    org.bukkit.event.EventException
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
            at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
            at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
            at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
            at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1109)
            at net.minecraft.server.Packet102WindowClick.handle(SourceFile:29)
            at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
            at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
            at net.minecraft.server.ServerConnection.b(SourceFile:35)
            at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
            at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:581)
            at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
            at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
            at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
            at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
    Caused by: java.lang.NullPointerException
            at org.bukkit.craftbukkit.inventory.CraftItemStack.setAmount(CraftItemStack.java:114)
            at de.funkyclan.mc.RepairRecipe.Listener.CraftingListener.onInventoryEvent(CraftingListener.java:92)
            at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:601)
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
            ... 14 more
```

**Comment by attrib** [comment]
Fixed in v0.3.1.
