### ISSUE TITLE
MC 1.5.1

### ISSUE THREAD

**Issue by attrib** [attrib/RepairRecipe#25]
I've been getting this error on starup out of the blue. Any ideas??

```
2013-03-26 22:18:59 [SEVERE] Could not load 'plugins\RepairRecipe-0.4.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException: class de.funkyclan.mc.RepairRecipe.RepairRecipe
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugins(CraftServer.java:262)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.<init>(CraftServer.java:240)
    at net.minecraft.server.v1_5_R2.PlayerList.<init>(PlayerList.java:55)
    at net.minecraft.server.v1_5_R2.DedicatedPlayerList.<init>(SourceFile:11)
    at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:109)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:385)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ClassCastException: class de.funkyclan.mc.RepairRecipe.RepairRecipe
    at java.lang.Class.asSubclass(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:174)
    ... 9 more
```

Can you please post further information - which dev version zou are using exaclty (eg. craftbukkit-1.5.1-R0.1-20130331.183223-29) and the full log?

**Comment by attrib** [comment]
This should be fixed I think.
Otherwise reopen,
